FROM node:17.3.0-alpine as build

WORKDIR /app
EXPOSE 3000

COPY package*.json /app/
COPY tsconfig.json /app/

COPY . /app/

RUN npm install
RUN npm run build

#nginx
FROM nginx:alpine

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/out /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]